package com.project.userservice.service;

import com.project.userservice.dto.UserDto;
import com.project.userservice.entity.User;
import com.project.userservice.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Optional;

@Service
@Transactional
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;

    @Autowired
    public UserServiceImpl(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @Override
    public UserDto createUser(UserDto userDto) {
        User user = toEntity(userDto);
        User saved = userRepository.save(user);
        return toDto(saved);
    }

    @Override
    public UserDto getUser(int id) {
        Optional<User> opt = userRepository.findById(id);
        return opt.map(this::toDto).orElse(null);
    }

    private UserDto toDto(User user) {
        if (user == null) return null;
        return new UserDto(user.getFirstname(), user.getLastname(), user.getUsername(), user.getPassword(), user.getEmail(), user.getPhone());
    }

    private User toEntity(UserDto dto) {
        if (dto == null) return null;
        User u = new User();
        // id is generated by the persistence provider, do not set from DTO
        u.setFirstname(dto.firstname());
        u.setLastname(dto.lastname());
        u.setUsername(dto.username());
        u.setPassword(dto.password());
        u.setEmail(dto.email());
        u.setPhone(dto.phone());
        return u;
    }
}
