package com.project.userservice.service;

import com.project.userservice.dto.UserDto;
import com.project.userservice.entity.User;
import com.project.userservice.entity.Session;
import com.project.userservice.repository.UserRepository;
import com.project.userservice.repository.SessionRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@Transactional
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;
    private final SessionRepository sessionRepository;

    @Autowired
    public UserServiceImpl(UserRepository userRepository, SessionRepository sessionRepository) {
        this.userRepository = userRepository;
        this.sessionRepository = sessionRepository;
    }

    @Override
    public UserDto createUser(UserDto userDto) {
        User user = toEntity(userDto);
        User saved = userRepository.save(user);
        return toDto(saved);
    }

    @Override
    public UserDto getUser(Long id) {
        Optional<User> opt = userRepository.findById(id);
        return opt.map(this::toDto).orElse(null);
    }

    @Override
    public List<UserDto> getAllUsers() {
        List<User> users = userRepository.findAll();
        return users.stream().map(this::toDto).collect(Collectors.toList());
    }

    @Override
    public UserDto updateUser(Long id, UserDto userDto) {
        Optional<User> opt = userRepository.findById(id);
        if (opt.isEmpty()) return null;
        User existing = opt.get();
        // update fields
        existing.setFirstname(userDto.firstname());
        existing.setLastname(userDto.lastname());
        existing.setUsername(userDto.username());
        existing.setPassword(userDto.password());
        existing.setEmail(userDto.email());
        existing.setPhone(userDto.phone());
        User saved = userRepository.save(existing);
        return toDto(saved);
    }

    @Override
    public boolean deleteUser(Long id) {
        Optional<User> opt = userRepository.findById(id);
        if (opt.isEmpty()) {
            return false;
        }
        userRepository.deleteById(id);
        return true;
    }

    @Override
    public String login(String email, String password) {
        Optional<User> opt = userRepository.findAll().stream().filter(u -> email.equals(u.getEmail())).findFirst();
        if (opt.isEmpty()) return null;
        User user = opt.get();
        if (!user.getPassword().equals(password)) return null;
        String token = UUID.randomUUID().toString();
        Session session = new Session();
        session.setToken(token);
        // Convert user id (Long) to Integer for session.userId
        Long uid = user.getId();
        session.setUserId(uid == null ? null : uid.intValue());
        sessionRepository.save(session);
        return token;
    }

    @Override
    public boolean logout(String token) {
        Optional<Session> opt = sessionRepository.findByToken(token);
        if (opt.isEmpty()) return false;
        sessionRepository.delete(opt.get());
        return true;
    }

    private UserDto toDto(User user) {
        if (user == null) return null;
        return new UserDto(user.getFirstname(), user.getLastname(), user.getUsername(), user.getPassword(), user.getEmail(), user.getPhone());
    }

    private User toEntity(UserDto dto) {
        if (dto == null) return null;
        User u = new User();
        // id is generated by the persistence provider, do not set from DTO
        u.setFirstname(dto.firstname());
        u.setLastname(dto.lastname());
        u.setUsername(dto.username());
        u.setPassword(dto.password());
        u.setEmail(dto.email());
        u.setPhone(dto.phone());
        return u;
    }
}
